<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Xu Zhang">

<title>How does register predict the effects of language-internal constraints on people’s probabilistic genitive expressions in American English?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="Paper_files/libs/clipboard/clipboard.min.js"></script>
<script src="Paper_files/libs/quarto-html/quarto.js"></script>
<script src="Paper_files/libs/quarto-html/popper.min.js"></script>
<script src="Paper_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Paper_files/libs/quarto-html/anchor.min.js"></script>
<link href="Paper_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Paper_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Paper_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Paper_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Paper_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#literature-review" id="toc-literature-review" class="nav-link" data-scroll-target="#literature-review">Literature Review</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a>
  <ul class="collapse">
  <li><a href="#corpus-data" id="toc-corpus-data" class="nav-link" data-scroll-target="#corpus-data">Corpus data</a></li>
  <li><a href="#data-extraction" id="toc-data-extraction" class="nav-link" data-scroll-target="#data-extraction">Data extraction</a></li>
  <li><a href="#conditional-factors-and-distributional-analysis" id="toc-conditional-factors-and-distributional-analysis" class="nav-link" data-scroll-target="#conditional-factors-and-distributional-analysis">Conditional factors and distributional analysis</a></li>
  </ul></li>
  <li><a href="#results-presentation" id="toc-results-presentation" class="nav-link" data-scroll-target="#results-presentation">Results presentation</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#answering-questions" id="toc-answering-questions" class="nav-link" data-scroll-target="#answering-questions">Answering questions</a></li>
  <li><a href="#comparing-with-previous-studies" id="toc-comparing-with-previous-studies" class="nav-link" data-scroll-target="#comparing-with-previous-studies">Comparing with previous studies</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">How does register predict the effects of language-internal constraints on people’s probabilistic genitive expressions in American English?</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Xu Zhang </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>English genitive expression has been adopted in a wide range of variationist studies to map out people’s probabilistic grammars across different varieties and with the change of time. Through the analysis of English users’ probabilistic choice of genitive variants, variationists have revealed many tendencies in English development, for instance colloquialisation of writing texts and Americanisation of other World Englishes. In addition, the research on varied registers found the economisation of genitive expression in Press English, which is attracting increased interest in recent studies. Despite abundant discussion about genitive as an alternation in variationist studies, register is still underrepresented as a predictor of the effect size of language-internal constraints. This might be caused by the conflict between the philosophies underpinning register and variationist studies. In fact, register studies focus on the aggregation of functional features. This is contradictory to the purpose of variationist studies which investigate the variation between different ways of achieving the same function <span class="citation" data-cites="szmrecsanyi_register_2019">(<a href="#ref-szmrecsanyi_register_2019" role="doc-biblioref">Szmrecsanyi 2019</a>)</span>. Given this conflict, register in variationist studies is treated as an external constraint predicting people’s choice of linguistically equivalent expressions in dialectic studies.</p>
<p>However, recent studies have revealed that register indeed interacts with internal predictors in people’s probabilistic choice between English dative alternatives <span class="citation" data-cites="seoane_chapter_2021">(<a href="#ref-seoane_chapter_2021" role="doc-biblioref">Engel et al. 2021</a>)</span>and genitive variants in American English. Taking this inspiration, the current study is intended to explore similar possibilities by looking at English users’ genitive expressions in a different corpus. Based on previous conclusions, this article is meant to investigate: 1) do registers predict the effects of language-internal predictors on probabilistic genitive expressions? 2) which constraints are particularly variable across registers? To realise these measurements, we chose to fit the logistic regression model into the annotated data using R since it is capable of directly and accurately estimating the effect sizes and directions of the chosen language-internal constraints. To visualise the interaction of register and the other factors, this study uses the effects package in R to plot these interactions out. The results will directly answer the two questions. At the same time, the final results will be compared with a precedented study that studied the pressure of modes and registers in predicting genitive variants in American English <span class="citation" data-cites="grafmiller_variation_2014">(<a href="#ref-grafmiller_variation_2014" role="doc-biblioref">Grafmiller 2014</a>)</span> for more insights. At the end, the essay will discuss the possibility of looking at registers from a variationist perspective, although the topic has traditionally been examined from a multidimensional perspective <span class="citation" data-cites="biber_variation_1988">(<a href="#ref-biber_variation_1988" role="doc-biblioref">Biber 1988</a>)</span>.</p>
</section>
<section id="literature-review" class="level2">
<h2 class="anchored" data-anchor-id="literature-review">Literature Review</h2>
<p>The main focus of variationist sociolinguistics is to figure out the mechanism underpinning people’s use of formally different constructions to express the same meaning <span class="citation" data-cites="szmrecsanyi_variation-based_2019">(e.g. <a href="#ref-szmrecsanyi_variation-based_2019" role="doc-biblioref">Szmrecsanyi, Grafmiller, and Rosseel 2019</a>)</span>. Variationists endeavour to detect people’s probabilistic choice between interchangeable morphosyntactic structures under the influence of both language-internal (i.e.&nbsp;constituent length) and language-external constraints (i.e.&nbsp;gender). Through measuring the effect sizes of the listed factors, it is possible to reveal speakers’ probabilistic grammar which will potentially indicate people’s cognitive process, societal change in the postcolonial age as well as linguistic phenomena including the indigenisation of a language and the economisation of language used in particular industries <span class="citation" data-cites="gardner2021 grafmiller_variation_2014 szmrecsanyi_around_2016">(e.g. <a href="#ref-gardner2021" role="doc-biblioref">Gardner et al. 2021</a>; <a href="#ref-grafmiller_variation_2014" role="doc-biblioref">Grafmiller 2014</a>; <a href="#ref-szmrecsanyi_around_2016" role="doc-biblioref">Szmrecsanyi et al. 2016</a>)</span>. Among the most widely tested morphosyntactic structures, the English genitive alternation is the most thoroughly researched.</p>
<p>English <em>s</em>-genitive and <em>of</em>-genitive structures are two prototypical nominal devices that express possessive relationships (e.g.&nbsp;<em>the company’s legal status</em> vs.&nbsp;<em>the legal status of the company</em>) <span class="citation" data-cites="rosenbach_genitive_2002">(<a href="#ref-rosenbach_genitive_2002" role="doc-biblioref">Rosenbach 2002a</a>)</span>. In this nominal construction, two noun phrases, the company and the legal status, constitute the possessive relationship, and they are named the “possessor” and the “possesssum” respectively <span class="citation" data-cites="rosenbach_genitive_2002">(<a href="#ref-rosenbach_genitive_2002" role="doc-biblioref">Rosenbach 2002a</a>)</span>. These two constructions are interchangeable because the only difference lies in the relational markers, s and of. The semantic meaning is not changed either when the possessor precedes the possessum in the <em>s</em>-genitive construction or in reverse order in the <em>of</em>-genitive construction <span class="citation" data-cites="rosenbach_genitive_2002">(<a href="#ref-rosenbach_genitive_2002" role="doc-biblioref">Rosenbach 2002a</a>)</span>. In previous analyses, the diachronic development of the two structures attracted a significant amount of interest <span class="citation" data-cites="rosenbach_genitive_2002">(<a href="#ref-rosenbach_genitive_2002" role="doc-biblioref">Rosenbach 2002a</a>)</span>. Those studies mainly focused on factors, including animacy, weight, economic motivation, and how they impact public choice making between the two different expressions <span class="citation" data-cites="grafmiller_variation_2014">(e.g. <a href="#ref-grafmiller_variation_2014" role="doc-biblioref">Grafmiller 2014</a>)</span>. In variationist studies, English genitive expression is widely adopted to model English speakers’ probabilistic grammar across regional varieties, genres and different time periods <span class="citation" data-cites="grafmiller_variation_2014 szmrecsanyi_around_2016">(<a href="#ref-grafmiller_variation_2014" role="doc-biblioref">Grafmiller 2014</a>; <a href="#ref-szmrecsanyi_around_2016" role="doc-biblioref">Szmrecsanyi et al. 2016</a>)</span>.</p>
<p>Previous studies have revealed numerous factors that could influence speakers’ choice between the two genitive expressions and the most influential one is proven to be animacy of possessor as the <em>s</em>-genitive is predominantly favoured by animate and topical possessors in a prototypical possessive relationship <span class="citation" data-cites="rosenbach_genitive_2002">(<a href="#ref-rosenbach_genitive_2002" role="doc-biblioref">Rosenbach 2002a</a>)</span>. However, recently studies show that the <em>s</em>-genitive is extended to inanimate possessors, for instance, <em>Germany’s chancellor</em> <span class="citation" data-cites="rosenbach_genitive_2002">(<a href="#ref-rosenbach_genitive_2002" role="doc-biblioref">Rosenbach 2002a</a>)</span>. This tendency, however, differs across geographical varieties as well as registers. As evidenced by <span class="citation" data-cites="hinrichs_recent_2007">Hinrichs and Szmrecsanyi (<a href="#ref-hinrichs_recent_2007" role="doc-biblioref">2007</a>)</span>, American English exhibits a greater affinity for the <em>s</em>-genitive than British English and written texts also show a preference for this form of expression. These phenomena are termed as Americanisation and Colloquialisation <span class="citation" data-cites="hinrichs_recent_2007">(<a href="#ref-hinrichs_recent_2007" role="doc-biblioref">Hinrichs and Szmrecsanyi 2007</a>)</span>. The shift to <em>s</em>-genitive even with inanimate possessors has been proposed as economically motivated as the <em>s</em>-genitive is more economical than its counterpart especially when the noun phrase possessor occurs frequently in the text as a thematic one <span class="citation" data-cites="hinrichs_recent_2007">(<a href="#ref-hinrichs_recent_2007" role="doc-biblioref">Hinrichs and Szmrecsanyi 2007</a>)</span>. This trend is increasingly seen in press texts <span class="citation" data-cites="grafmiller_variation_2014">(<a href="#ref-grafmiller_variation_2014" role="doc-biblioref">Grafmiller 2014</a>)</span>.</p>
<p>In addition, previous literature elaborated on how people’s preferences for a particular genitive variant change with time, across geographical locations and between different registers. Inspired by the interaction between registers and English speakers’ probabilistic choice of genitive expression, this article is intended to zoom into American English to determine whether registers predict the effect of language-internal constraints on people’s genitive expressions. At the same time, it is determined to identify which probabilistic constraints are particularly variable across registers. To differentiate this study, this article adopted a distinct classification of registers based on the provision of tokens from a less frequently tested database, the Corpus of Contemporary American English (COCA).</p>
<p>Register is strongly associated with situational context, linguistic features and the functional correlation between the situational context and the pervasive linguistic features <span class="citation" data-cites="biber2019">(<a href="#ref-biber2019" role="doc-biblioref">Biber and Conrad 2019</a>)</span>. Additionally, registers could be defined according to various levels of specificity. For example, academic prose and the method section of experimental medical research articles are associated with their own registers <span class="citation" data-cites="biber2019">(<a href="#ref-biber2019" role="doc-biblioref">Biber and Conrad 2019</a>)</span>. According to <span class="citation" data-cites="biber_variation_1988">Biber (<a href="#ref-biber_variation_1988" role="doc-biblioref">1988</a>)</span>, the styles, registers and genres of text types cannot be distinguished according to dichotomous parameters. Different texts may show prominence in the cooccurrence of functional features (e.g.&nbsp;passive and nominalisation in academic prose) but most of the text types present complexity in terms of functional features under the influence of varied situational contexts. For example, academic lectures as a spoken register is more literate than personal letters despite being a written text. Furthermore, there is no agreement on the absolute distinction between speech and written registers except for the prototypical ones. Therefore, instead of dividing texts into discrete poles, Biber adopted continuum dimensions which determine the communicative properties of a wide range of spoken and written texts.</p>
<p>The selection of registers in this article is based on both the functional features and situational contexts of texts. According to factor analysis of the dimensional distribution of various texts in Biber’s study, academic prose and press reportage are identified as informational texts with a high absolute value in Dimension One, involvement vs.&nbsp;information-orientation texts. As such, COCA’s News and Academic scripts are selected to represent a register of literate writing. Another register with a high degree of internal uniformity is online texts which encompass blog and web-general scripts. Details of the internal homogeneity of the chosen registers will be specified in the methodology section.</p>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">Methodology</h2>
<p>Keeping in line with previous variationist sociolinguistic studies, this article compared two registers, replacing the traditional geographical varieties, using the framework of Comparative Sociolinguistics in order to measure the effect sizes, direction, and significance of the selected predictors <span class="citation" data-cites="tagliamonte2012 grafmiller2018">(<a href="#ref-tagliamonte2012" role="doc-biblioref">Tagliamonte 2012</a>; <a href="#ref-grafmiller2018" role="doc-biblioref">Grafmiller and Szmrecsanyi 2018</a>)</span>. We adopted a method used in dialect studies in this analysis since recent examples have revealed how registers and modality influence people’s probabilistic expressions <span class="citation" data-cites="seoane_chapter_2021">(<a href="#ref-seoane_chapter_2021" role="doc-biblioref">Engel et al. 2021</a>)</span>.</p>
<p>To avoid predictor multicollinearity and data overfitting <span class="citation" data-cites="szmrecsanyi_around_2016">(<a href="#ref-szmrecsanyi_around_2016" role="doc-biblioref">Szmrecsanyi et al. 2016</a>)</span>, this study fits the logistic regression model to richly annotated data for a more accurate and robust prediction, with the help of the <em>glm()</em> function in R. In doing so, all factors are specified in the formula followed by the addition of the “family = binomial” argument. The <em>summary()</em> function presents coefficients of specified predictors indicating the effect sizes and directions of those factors. It should be noted that the concordance index <em>C</em> is generated to demonstrate how well the model discriminates between the two comparisons of the predicted probabilities of variants with the real occurrences of the corresponding ones in the selected data. A <em>C</em> score higher than 0.9 indicates outstanding discrimination but a value between 0.8 and 0.9 is also excellent <span class="citation" data-cites="levshina_how_2015">(<a href="#ref-levshina_how_2015" role="doc-biblioref">Levshina 2015</a>)</span>.</p>
<p>To visualise the outcome, Partial Effect Plots are generated to visualise the comparison of register-specific constraint effects and how they influence people’s choice-making in each register. All results from the logistic regression model will be visualised via the <em>allEffects()</em> combined with <em>plot()</em> functions. In this way, all interactions between registers and language-internal predictors will be plotted out. It should be noted that the random distribution of <em>s</em>- and <em>of</em>-genitive variants in the chosen two registers is not the focus of this research. Instead, it looks at the comparison of the effect size of predictors (i.e.&nbsp;language-internal constraints) between two registers. In this case, statistical evidence of constraint effects is imperative, so, this study uses Boxplot for continuum and cross table for binary predictors to support comparisons between their performance in two registers.</p>
<section id="corpus-data" class="level3">
<h3 class="anchored" data-anchor-id="corpus-data">Corpus data</h3>
<p>To achieve our goal of comparing the effects of probabilistic constraints across registers, this study selected the Corpus of Contemporary American English (COCA), so as to narrow the focus to mere American English. In doing so, it optimally diminished the influence of variety in this comparison. In particular, this research covers data from two registers, literate writing (news and academic writing) and online text (blog and web-general content). It is crucial to emphasise that the chosen registers demonstrate a high degree of inner homogeneity, which increases their significance for a sociolinguistic research. This conclusion is made based on a review of the composition of each genre in the COCA corpus. Other genres, including fiction and magazines as written texts, are excluded because they vary drastically in terms of their communicative purpose with the change of themes (e.g.&nbsp;romantic fiction vs.&nbsp;science fiction). The spoken register includes TV, movie, and news reports, which are arguably poor prototypes in terms of their functional features and situational contexts. As a result, they are eliminated from this research. As a result of the limited space of this article, the study selected about 970 tokens to compose the database, with approximately 500 tokens per register. The distribution of two variants in registers is presented in the following table.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 970   7</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Cell Contents
|-------------------------|
|                   Count |
|          Column Percent |
|-------------------------|

Total Observations in Table:  970 

                 | dataset$Genitive_type 
dataset$Register |   0f_gen  |    s_gen  | Row Total | 
-----------------|-----------|-----------|-----------|
              LT |      275  |      251  |      526  | 
                 |     57.7% |     50.9% |           | 
-----------------|-----------|-----------|-----------|
              OT |      202  |      242  |      444  | 
                 |     42.3% |     49.1% |           | 
-----------------|-----------|-----------|-----------|
    Column Total |      477  |      493  |      970  | 
                 |     49.2% |     50.8% |           | 
-----------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
</section>
<section id="data-extraction" class="level3">
<h3 class="anchored" data-anchor-id="data-extraction">Data extraction</h3>
<p>Data are extracted using the function of List for the <em>s</em>-genitive while the <em>of</em>-genitive is detected via the Key Word in Context (KWIC) function, with restrictions on ‘section’ to specify the two registers. In fact, COCA’s two functions are not intelligent enough to extract the targeted expressions, so manual filtering is required. The standard for exclusion is adopted from previous analyses and the findings of COCA in particular. Precisely, a token considered interchangeable should be freely converted from one variant to the other without modification of the other lexical items in the construction, and the only exception is the obligatory deletion of determiners in possessum NPs (e.g.&nbsp;<em>the principle of the country</em> vs.&nbsp;<em>The country’s principle</em>) <span class="citation" data-cites="grafmiller_variation_2014">(<a href="#ref-grafmiller_variation_2014" role="doc-biblioref">Grafmiller 2014</a>)</span>. Items belonging to the following groups are eliminated, namely, constructions lacking an overt possessum, the possessor being a classifier instead of a referential, contractions, titles, names, quotations, fixed expressions (e.g.&nbsp;<em>Murphy’s law</em>) and collective possessums (e.g.&nbsp;<em>a group of students</em>). Additionally, tokens containing pronominal possessors are also removed from the dataset as it demonstrates clear preferences for the pre-nominal position in written texts according to <span class="citation" data-cites="jucker1993">Jucker (<a href="#ref-jucker1993" role="doc-biblioref">1993</a>)</span>. Furthermore, pronominal <em>of</em>-genitives are prohibited in prescriptive literature <span class="citation" data-cites="hinrichs_recent_2007">(<a href="#ref-hinrichs_recent_2007" role="doc-biblioref">Hinrichs and Szmrecsanyi 2007</a>)</span>. Given these arguments, pronominal tokens are regarded as non-interchangeable and thus removed from this research.</p>
</section>
<section id="conditional-factors-and-distributional-analysis" class="level3">
<h3 class="anchored" data-anchor-id="conditional-factors-and-distributional-analysis">Conditional factors and distributional analysis</h3>
<p>Previous literature of English genitive studies has proven that the lexical class of the possessor is the most influential factor that predicts speakers’ choice between the two variants <span class="citation" data-cites="hinrichs_recent_2007">(<a href="#ref-hinrichs_recent_2007" role="doc-biblioref">Hinrichs and Szmrecsanyi 2007</a>)</span>. In detail, animate possessors, including both humans and animals, favour <em>s</em>-genitive <span class="citation" data-cites="rosenbach2002">(<a href="#ref-rosenbach2002" role="doc-biblioref">Rosenbach 2002b</a>)</span>. However, due to the limited space for elaboration, the internal hierarchy of animacy possessors, ranging from human to collective entities, is not specified in this study. To testify whether animacy plays a role in this research, all tokens are manually annotated according to the classification of possessors, as a binary predictor, animate vs.&nbsp;inanimate. The following table crosstabulates the influence of animacy on people’s choice of the two variants based on numerical calculation of occurrences of animate and inanimate possessors. It is presented that the chosen registers, generally, disfavour animate possessors, while animate possessors mainly occur in the <em>s</em>-genitive variant.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 970   7</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Cell Contents
|-------------------------|
|                   Count |
|          Column Percent |
|-------------------------|

Total Observations in Table:  970 

                         | dataset$Genitive_type 
dataset$Pssessor_animacy |   0f_gen  |    s_gen  | Row Total | 
-------------------------|-----------|-----------|-----------|
                       N |      444  |      172  |      616  | 
                         |     93.1% |     34.9% |           | 
-------------------------|-----------|-----------|-----------|
                       Y |       33  |      321  |      354  | 
                         |      6.9% |     65.1% |           | 
-------------------------|-----------|-----------|-----------|
            Column Total |      477  |      493  |      970  | 
                         |     49.2% |     50.8% |           | 
-------------------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<p>Next to animacy is the final sibilant pronunciation of possessors as it is concluded that the occurrence of the final sibilance tries to avoid a closely following up sibilant pronunciation and thus discourages the construction of <em>s</em>-genitive, which is considered a ‘phonological horror aequi effect’ <span class="citation" data-cites="hinrichs_recent_2007">(<a href="#ref-hinrichs_recent_2007" role="doc-biblioref">Hinrichs and Szmrecsanyi 2007</a>)</span>. Possessors ending with segments including <s>, <z>, <ce>, <sh> and <tch> are regarded as ‘final sibilant present’, coded as “Y”, while the remaining are coded as ‘N’ for further processing. As shown in the following table, there are only a small proportion of sibilant possessors in the selected database while they mainly occur in <em>of</em>-genitive expressions.</tch></sh></ce></z></s></p><s>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 970   7</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Cell Contents
|-------------------------|
|                   Count |
|          Column Percent |
|-------------------------|

Total Observations in Table:  970 

                        | dataset$Genitive_type 
dataset$Final_sibilancy |   0f_gen  |    s_gen  | Row Total | 
------------------------|-----------|-----------|-----------|
                      N |      332  |      474  |      806  | 
                        |     69.6% |     96.1% |           | 
------------------------|-----------|-----------|-----------|
                      Y |      145  |       19  |      164  | 
                        |     30.4% |      3.9% |           | 
------------------------|-----------|-----------|-----------|
           Column Total |      477  |      493  |      970  | 
                        |     49.2% |     50.8% |           | 
------------------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<p>Another significant factor governing the use of the English language is the end weight principle which states that language users are more likely to put ‘heavier’ and more complex constituents after shorter and easier ones so as to leave more time for processing <span class="citation" data-cites="hinrichs_recent_2007">(<a href="#ref-hinrichs_recent_2007" role="doc-biblioref">Hinrichs and Szmrecsanyi 2007</a>)</span>. By applying the end weight principle to genitive analysis, it is claimed that longer possessors usually favour the <em>of</em>-genitive construction while heavier possessors typically prefer the <em>s</em>-genitive expression, since such preferences postpone the occurrence of longer constituents, giving language users enough time to process the information. As demonstrated in the following boxplots, the mean length of possessors in of-genitive is about 2.4 words while it is 1.6 in <em>s</em>-genitive. In addition to that, the mean length of possessum phrases is 2.1 and 1.7 words in of- and <em>s</em>-genitives respectively. This distribution of possessor and possessum word length coincides with the previous conclusions that <em>of</em>-genitive constructions are typically associated with longer possessors, but <em>s</em>-genitives occur along with longer possessums. In addition, the boxplots indicate that the distribution of possessum length is more intense than that of possessor word length, which shows larger deviation in the two variants of genitive expressions within the dataset.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Genitive_type Possessor_length
1        0f_gen         2.406709
2         s_gen         1.606491</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Paper_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Genitive_type Possessum_length
1        0f_gen         2.113208
2         s_gen         1.774848</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Paper_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A final predictor lies in the semantic relation, which is coded according to the analyses of <span class="citation" data-cites="grafmiller_variation_2014">Grafmiller (<a href="#ref-grafmiller_variation_2014" role="doc-biblioref">2014</a>)</span> and <span class="citation" data-cites="rosenbach_genitive_2002">Rosenbach (<a href="#ref-rosenbach_genitive_2002" role="doc-biblioref">2002a</a>)</span>. It is collapsed into a binary category of prototypical vs non-prototypical genitives and those prototypical genitives are characterised by legal ownership, kinship, family ties, body parts, and part-whole relationships (e.g.&nbsp;house of Tom, Tom’s children, The fish’s mouth, the start of the journey), coded as “Y”. The non-prototypical genitives are the ones that fall outside the listed relations, coded as “N”. In the following table, non-prototypical genitive relations make up the majority, which are evenly distributed between the two genitive variants.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 970   7</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Cell Contents
|-------------------------|
|                   Count |
|          Column Percent |
|-------------------------|

Total Observations in Table:  970 

                        | dataset$Genitive_type 
dataset$Prototypicality |   0f_gen  |    s_gen  | Row Total | 
------------------------|-----------|-----------|-----------|
                      N |      394  |      385  |      779  | 
                        |     82.6% |     78.1% |           | 
------------------------|-----------|-----------|-----------|
                      Y |       83  |      108  |      191  | 
                        |     17.4% |     21.9% |           | 
------------------------|-----------|-----------|-----------|
           Column Total |      477  |      493  |      970  | 
                        |     49.2% |     50.8% |           | 
------------------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
</s></section><s>
</s></section><s>
<section id="results-presentation" class="level2">
<h2 class="anchored" data-anchor-id="results-presentation">Results presentation</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Genitive_type ~ Pssessor_animacy + Final_sibilancy + 
    Prototypicality + Possessor_length + Possessum_length + Register + 
    Register * Pssessor_animacy + Register * Final_sibilancy + 
    Register * Prototypicality + Register * Possessor_length + 
    Register * Possessum_length, family = binomial, data = dataset)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.9537  -0.6698   0.1181   0.3931   3.1129  

Coefficients:
                             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                    1.3239     0.3835   3.453 0.000555 ***
Pssessor_animacyY              2.8827     0.3322   8.679  &lt; 2e-16 ***
Final_sibilancyY              -3.6972     0.4936  -7.490 6.87e-14 ***
PrototypicalityY              -0.1794     0.2886  -0.622 0.534257    
Possessor_length              -0.6697     0.1365  -4.906 9.28e-07 ***
Possessum_length              -0.1663     0.1024  -1.625 0.104226    
RegisterOT                     1.6193     0.7187   2.253 0.024242 *  
Pssessor_animacyY:RegisterOT   1.0608     0.5469   1.940 0.052408 .  
Final_sibilancyY:RegisterOT    1.7649     0.7286   2.422 0.015424 *  
PrototypicalityY:RegisterOT   -0.2960     0.4853  -0.610 0.541909    
Possessor_length:RegisterOT   -0.6410     0.2776  -2.309 0.020925 *  
Possessum_length:RegisterOT   -0.4470     0.2084  -2.145 0.031927 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1344.44  on 969  degrees of freedom
Residual deviance:  733.67  on 958  degrees of freedom
AIC: 757.67

Number of Fisher Scoring iterations: 6</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          C         Dxy           n     Missing 
  0.9083032   0.8166065 970.0000000   0.0000000 </code></pre>
</div>
</div>
<p>Taking <em>of</em>-genitive as the reference, the model estimates precise effect sizes and directions of each predictor through the logit numbers, positive number favouring <em>s</em>-genitive while negative figures favour of-genitive. This model provides outstanding prediction with a <em>c</em>-value above 0.9. The first number, 1.32, estimates the log odds when all predictors are at the reference levels. To be specific, the positive number, 2.88, indicates that Possessor Animacy robustly prefers <em>s</em>-genitive in this model, while Final Sibilancy is just the opposite with a negative 3.69 estimated number because it strongly dislikes <em>s</em>-genitive. Register OT, with literate text register as default, shows considerable preference for <em>s</em>-genitive. Furthermore, Possessor and Possessum Length discourage <em>s</em>-genitive but to varying degrees. It should be noted that Prototypicality is marginalised with a slight disfavour for the <em>s</em>-genitive expression but this result is unreliable as the p-value is higher than 0.5, indicating that this result might be obtained by chance.</p>
<p>The results of register-specific predictors automatically set literate text register as the default, while the results show how conditional predictors affect the choice of genitive variants in online text register. The most noticeable difference is that Final Sibilancy displays an opposite direction in this register than in the overall dataset as it prefers <em>s</em>-genitive in the online register. Possessor Animacy still favours <em>s</em>-genitive in online texts, but it displays a weaker preference. Similarly, Possessor Length and Possessum Length demonstrate the same direction but Possessum Length shows a marginally stronger dislike for <em>s</em>-genitive in this specific register. Prototypicality presents an even slighter disfavour for <em>s</em>-genitive than in the entire data but this result is equally unreliable.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Paper_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The particle effect plot provides a clear visualisation of how these factors influence public choices of the two genitive constructions when expressing a possessive relationship. The <em>allEffect()</em> function converts log odds to probability. Then it multiplies the model matrix values by their respective coefficients and sums them all together. In the end, these plots are generated based on various combinations of internal predictor and register scores. They show how the probability of choosing <em>s</em>-genitive changes for various combinations of internal predictor and register scores. For instance, the plot for Possessor Animacy and Register is produced based on various combinations of Possessor Animacy and Register scores. The x-axis in each plot indicates the values automatically selected from the predictor when the register score is fixed denoting a particular register in which this interaction happens. The y-axis presents the probability of choosing <em>s</em>-genitive in this study as <em>of</em>-genitive is set as the reference. It is seen that the probability increases when the possessor shifts from inanimate to animate in both Register LT and OT.</p>
<p>It should be noted that there are two types of predictors, binary and numeric, which lead to different forms of presentation. Binary factors, though calculated with scores, the x-axis requires named vectors, such as ‘Y’ and ‘N’, while numeric factors are presented in numbers. However, it should be noticed that the light blue area is the confidence band. As it widens, this indicates that there are few subjects with high scores in Possessor and Possessum Length and hence less confidence in the prediction of probability.</p>
<p>Based on these results, Possessor and Possessum Length perform drastically differently in the two registers. In the literary writing register, there is a relatively mild decrease in the probability of choosing an <em>s</em>-genitive as Possessor and Possessum length increase. By contrast, the online text register sees a more radical drop in probability. This implies that people are less likely to be impacted by the word length of noun phrases when deciding on a genitive variant as writing literate texts. Another striking phenomenon is observed in the interaction between Final Sibilancy and Registers. There is an indication that people are more likely to be affected by sibilant pronunciation when writing literate content as the probability of choosing <em>s</em>-genitive drops in LT register in a more radical manner than in OT register. Possessor Animacy influences people’s s-genitive choice in a positive way. Although there are some slight differences in the steepness of the slopes in the two registers, animacy has almost the same impact on people whether they are composing literate texts or delivering online content. Since the prediction of Prototypicality was proven to be without confidence, the plot for Prototypicality is thus ignored.</p>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="answering-questions" class="level3">
<h3 class="anchored" data-anchor-id="answering-questions">Answering questions</h3>
<p>Through the comparison between two registers, this study has proven that register predicts the effects of language-internal constraints that influence people’s probabilistic choice between two genitive expressions. This result is in line with the analysis of <span class="citation" data-cites="grafmiller_variation_2014">Grafmiller (<a href="#ref-grafmiller_variation_2014" role="doc-biblioref">2014</a>)</span>. The functional and situational features of registers, namely information-orientation and online texts, have unique properties for predicting the effect sizes of the chosen conditioning factors. In particular, it is evident that the effects of Final Sibilancy, Possessor and Possessum Length are variable with the change of registers in the present study.</p>
</section>
<section id="comparing-with-previous-studies" class="level3">
<h3 class="anchored" data-anchor-id="comparing-with-previous-studies">Comparing with previous studies</h3>
<p>It should, first, be noticed that this study generates different results from the analysis of the interaction between genres and modes of language production with language-internal constraints that influence people’s choice between <em>s</em>- and <em>of</em>-genitives in American English<span class="citation" data-cites="grafmiller_variation_2014">(<a href="#ref-grafmiller_variation_2014" role="doc-biblioref">Grafmiller 2014</a>)</span>. The previous study was conducted based on six different styles of written and spoken genitives from two corpora, the Switchboard corpus of American English and the Boston University Noun Phrase Corpus. Possessor Animacy was found to be the most influential predictor with an effect size about four times greater than that of Final Sibilancy. The current study, based on the data from COCA, produces an adverse result with Final Sibilancy exceeding Animacy as the most influential factor that predicts people’s genitive expressions. However, when examining the coefficients of Animacy and Final Sibilancy, the absolute numbers are closer in this study than in the previous research. This indicates similar effect sizes for the two predictors. It is seen that the impact of Animacy shrunk to below 3, but the absolute figure for Final Sibilancy increased to 3.69. The decrease of Animacy impact might be explained by the expansion of <em>s</em>-genitive to inanimate possessors. This weakens the influence of Animacy on people’s choice between the two variants. Additionally, even though in written texts, the phonological factor of Final Sibilancy gains dramatically in importance, particularly in literate texts. This phenomenon, however, might be unique to the chosen registers, which await further exploration.</p>
<p>As concluded in previous studies, written text dislikes the appearance of <em>s</em>-genitives. In this study, the literate register tends to favour <em>of</em>-genitive. Online text register, absent from the previous study, exhibited a preference for the <em>s</em>-genitive which distinguishes it from traditional writing texts. In this respect, the online register presents the quality of spoken genres in the analysis of <span class="citation" data-cites="grafmiller_variation_2014">Grafmiller (<a href="#ref-grafmiller_variation_2014" role="doc-biblioref">2014</a>)</span>. In addition, the end weight principle still plays a role in this analysis as the length ratio reports a favour for the <em>of</em>-genitive. Particle effect plots provide strong evidence of the interaction between registers and the effect of each predictor. Strikingly, the change of register has a significant impact on how the other language-internal constraints influence people’s probabilistic choice between two genitive constructions. The most striking change happened on Possessor and Possesum Length predictors. It is concluded that people are more sensitive to the length of possessors and possessums in choosing a genitive variant to express possessive relations when delivering online texts. This could be interpreted as the higher sensitivity of OT register to the end weight principle. An adverse tendency was spotted on Final Siblancy because people tend to be more sensitive to the sibilant pronunciation of possessors when composing possessive expressions in a literate context. From this comparison, it is noted that either the change of database or the reclassification of registers influences the interaction between the language-internal constraints and registers in predicting people’s probabilistic choice between two genitive variants. To explain these differences, more evidence from cognitive and perceptual perspectives is needed.</p>
<p>Lastly, the present results could be added to the conclusion of <span class="citation" data-cites="seoane_chapter_2021">Engel et al. (<a href="#ref-seoane_chapter_2021" role="doc-biblioref">2021</a>)</span> which studied how modes and registers influence people’s probabilistic choice between English dative variants. Together, they prove the same thing that linguistic variation across registers could be studied from a variationist perspective with the support of corpus studies on two grammatical alternations <span class="citation" data-cites="seoane_chapter_2021">(<a href="#ref-seoane_chapter_2021" role="doc-biblioref">Engel et al. 2021</a>)</span>. Based on the comparison with previous studies, the present study, at least, showed that online texts are close to spoken register, as demonstrated by the effect of processing-related constraints, namely, the length of constituents. By contrast, the information-oriented register demonstrates a higher sensitivity to a phonological factor, although it is in line with previous studies in which sibilant pronunciation disfavours <em>s</em>-genitive even in writing texts. However, more evidence, both theoretical and empirical, is needed to analyse these differences.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>This article presents a variationist study of people’s choice between the <em>s</em>- and <em>of</em>-genitive variants in American English with the intention of studying how a language-external constraint, register, and language-internal constraints interact. Based on previous literature, this article, first, specifies what a register is, as well as the composition of two registers employed in this study. Different from the mainstream classification of registers according to formality and channels of production, this article adopts a highly information-orientated register according to the dimensional analysis from the categorisation of <span class="citation" data-cites="biber_variation_1988">Biber (<a href="#ref-biber_variation_1988" role="doc-biblioref">1988</a>)</span>. Instead of comparing an interactive register with an information-oriented one, this study focused on a more internally homogenous provision of data in COCA, forming a comparison between an information-oriented and an online text register. This arrangement, at the same time, contributes to register studies as it proves the possibility of studying text types through a variationist perspective.</p>
<p>Regarding the choice of quantitative tools, the advantages of a logistic regression model lie in the fact that it provides both the strength and direction of predictors’ effects. This model has been proven to possess outstanding predictability with a c-value more than 0.9. According to the results, Possessor Animacy is the only predictor that strongly prefers <em>s</em>-genitive to <em>of</em>-genitive. Final Sibilancy is the strongest predictor in predicting the <em>of</em>-genitive expression. Possessor and Possessum Length both present disfavour for <em>s</em>-genitive but at varying strengths. The comparatively weakened force of Animacy in this analysis might be explained by the expansion of <em>s</em>-genitive increasingly to inanimate contexts. In addition to that, Register plays a vital role in predicting the genitive expressions while it is more meaningful to look into the interaction between registers and the other conditioning factors. From the partial effect plot, four feasible predictors demonstrate alternate impact patterns in two registers. This is extremely effective at testing the sensitivity of registers to predictors. Possessor and Possessum Length present slopes that decline at varying steepness with the change of register. This indicates that online texts are more sensitive to the length of noun phrase constituents, because the probability of choosing <em>s</em>-genitive drops more drastically in online texts than in the literate writing register. Finally, it is noteworthy that the probability of <em>s</em>-genitive expression drops more steeply in literate texts when Final Sibilancy occurs, which suggests literate texts are more sensitive to sibilant pronunciations than online content.</p>
<p>This study provides, to a limited extent, meaningful evidence regarding the interaction of registers with language-internal constraints. As a variationist study, it illustrates how five factors predict people’s choice between English genitive constructions. It also reveals the change in patterns of their effects in two specific registers. At the same time, it contributes to register study as it strengthens the idea that text types could be analysed from a variationist perspective except for the widely accepted multidimensional classification from <span class="citation" data-cites="biber_variation_1988">Biber (<a href="#ref-biber_variation_1988" role="doc-biblioref">1988</a>)</span>. However, this study could be improved in many ways. A drawback is the database’s lack of diversity and substantiality, which will necessitate a larger and more varied collection of datasets in future research.</p>

</section>

</s><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-biber_variation_1988" class="csl-entry" role="doc-biblioentry">
Biber, Douglas. 1988. <em>Variation Across Speech and Writing</em>. Cambridge [England] ; New York: Cambridge University Press.
</div>
<div id="ref-biber2019" class="csl-entry" role="doc-biblioentry">
Biber, Douglas, and Susan Conrad. 2019. <em>Register, Genre, and Style</em>. Second edition. Cambridge Textbooks in Linguistics. Cambridge, United Kingdom ; New York, NY: Cambridge University Press.
</div>
<div id="ref-seoane_chapter_2021" class="csl-entry" role="doc-biblioentry">
Engel, Alexandra, Jason Grafmiller, Laura Rosseel, Benedikt Szmrecsanyi, and Freek Van de Velde. 2021. <span>“Chapter 3. <span>How</span> Register-Specific Is Probabilistic Grammatical Knowledge?: <span>A</span> Programmatic Sketch and a Case Study on the Dative Alternation with <em>Give</em>.”</span> In <em>Studies in <span>Corpus</span> <span>Linguistics</span></em>, edited by Elena Seoane and Douglas Biber, 103:51–84. Amsterdam: John Benjamins Publishing Company. <a href="https://doi.org/10.1075/scl.103.03eng">https://doi.org/10.1075/scl.103.03eng</a>.
</div>
<div id="ref-gardner2021" class="csl-entry" role="doc-biblioentry">
Gardner, Matt Hunt, Eva Uffing, Nicholas Van Vaeck, and Benedikt Szmrecsanyi. 2021. <span>“Variation Isn<span>’</span>t That Hard: Morphosyntactic Choice Does Not Predict Production Difficulty.”</span> Edited by Stefan Th. Gries. <em>PLOS ONE</em> 16 (6): e0252602. <a href="https://doi.org/10.1371/journal.pone.0252602">https://doi.org/10.1371/journal.pone.0252602</a>.
</div>
<div id="ref-grafmiller_variation_2014" class="csl-entry" role="doc-biblioentry">
Grafmiller, Jason. 2014. <span>“Variation in <span>English</span> Genitives Across Modality and Genres.”</span> <em>English Language and Linguistics</em> 18 (3): 471–96. <a href="https://doi.org/10.1017/S1360674314000136">https://doi.org/10.1017/S1360674314000136</a>.
</div>
<div id="ref-grafmiller2018" class="csl-entry" role="doc-biblioentry">
Grafmiller, Jason, and Benedikt Szmrecsanyi. 2018. <span>“Mapping Out Particle Placement in Englishes Around the World. A Study in Comparative Sociolinguistic Analysis.”</span>
</div>
<div id="ref-hinrichs_recent_2007" class="csl-entry" role="doc-biblioentry">
Hinrichs, Lars, and Benedikt Szmrecsanyi. 2007. <span>“Recent Changes in the Function and Frequency of <span>Standard</span> <span>English</span> Genitive Constructions: A Multivariate Analysis of Tagged Corpora.”</span> <em>English Language and Linguistics</em> 11 (3): 437–74. <a href="https://doi.org/10.1017/S1360674307002341">https://doi.org/10.1017/S1360674307002341</a>.
</div>
<div id="ref-jucker1993" class="csl-entry" role="doc-biblioentry">
Jucker, A. 1993. <span>“The Genitive Versus the of-Construction in Newspaper Language.”</span> In, 12136. Heidelberg: Carl Winter.
</div>
<div id="ref-levshina_how_2015" class="csl-entry" role="doc-biblioentry">
Levshina, Natalia. 2015. <em>How to Do Linguistics with <span>R</span>: Data Exploration and Statistical Analysis</em>. Amsterdam ; Philadelphia: John Benjamins Publishing Company.
</div>
<div id="ref-rosenbach_genitive_2002" class="csl-entry" role="doc-biblioentry">
Rosenbach, Anette. 2002a. <em>Genitive Variation in <span>English</span>: Conceptual Factors in Synchronic and Diachronic Studies</em>. Topics in <span>English</span> Linguistics 42. Berlin ; New York: Mouton de Gruyter.
</div>
<div id="ref-rosenbach2002" class="csl-entry" role="doc-biblioentry">
———. 2002b. <em>Genitive Variation in English: Conceptual Factors in Synchronic and Diachronic Studies</em>. Topics in English Linguistics 42. Berlin ; New York: Mouton de Gruyter.
</div>
<div id="ref-szmrecsanyi_register_2019" class="csl-entry" role="doc-biblioentry">
Szmrecsanyi, Benedikt. 2019. <span>“Register in Variationist Linguistics.”</span> <em>Register Studies</em> 1 (1): 76–99. <a href="https://doi.org/10.1075/rs.18006.szm">https://doi.org/10.1075/rs.18006.szm</a>.
</div>
<div id="ref-szmrecsanyi_around_2016" class="csl-entry" role="doc-biblioentry">
Szmrecsanyi, Benedikt, Jason Grafmiller, Benedikt Heller, and Melanie Röthlisberger. 2016. <span>“Around the World in Three Alternations: <span>Modeling</span> Syntactic Variation in Varieties of <span>English</span>.”</span> <em>English World-Wide. A Journal of Varieties of English</em> 37 (2): 109–37. <a href="https://doi.org/10.1075/eww.37.2.01szm">https://doi.org/10.1075/eww.37.2.01szm</a>.
</div>
<div id="ref-szmrecsanyi_variation-based_2019" class="csl-entry" role="doc-biblioentry">
Szmrecsanyi, Benedikt, Jason Grafmiller, and Laura Rosseel. 2019. <span>“Variation-<span>Based</span> <span>Distance</span> and <span>Similarity</span> <span>Modeling</span>: <span>A</span> <span>Case</span> <span>Study</span> in <span>World</span> <span>Englishes</span>.”</span> <em>Frontiers in Artificial Intelligence</em> 2 (November): 23. <a href="https://doi.org/10.3389/frai.2019.00023">https://doi.org/10.3389/frai.2019.00023</a>.
</div>
<div id="ref-tagliamonte2012" class="csl-entry" role="doc-biblioentry">
Tagliamonte, Sali. 2012. <em>Variationist Sociolinguistics: Change, Observation, Interpretation</em>. Language in Society 40. Malden, MA: Wiley-Blackwell.
</div>
</div></section></div></main><s>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</s></div><s> <!-- /content -->



</s></body></html>